version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Checking current directory:
      - ls -la
      - echo Contents of app.py:
      - cat app.py
      - echo Running tests...
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - pytest -v --junitxml=reports/results.xml

  post_build:
    commands:
      - echo ✅ Build phase completed.

artifacts:
  files:
    - '**/*'
  base-directory: .

reports:
  pytest:
    files:
      - reports/results.xml
    discard-paths: yes
