version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running tests...
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - pytest --junitxml=reports/results.xml --tb=short
  post_build:
    commands:
      - echo ✅ Tests finished. Build complete.

artifacts:
  files:
    - '**/*'
  base-directory: .

reports:
  pytest:
    files:
      - "reports/results.xml"
    discard-paths: yes
